spring.datasource.url=jdbc:postgresql://localhost:5432/my_project_db
spring.datasource.username=postgres
spring.datasource.password=1607Vbkfyf!
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/master.xml
spring.jpa.hibernate.ddl-auto=none